version: '3'

services:
  # PostgreSQL database server
  psql:
    build:
      context: ./postgres
      dockerfile: Dockerfile.postgres
    environment:
      - PGDATA:/var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/pg_hba.conf:/var/lib/postgres/data/pg_hba.conf
      - ./data/pgdata:/pgdata
    restart: unless-stopped

  # Kristal API
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.web
    depends_on:
      - psql
    volumes:
      - ./site:/var/www
      - ./data:/var/data
    ports:
      - 4563:8080
    restart: unless-stopped

volumes:
  postgres:
